export const CLIENT_SERVICES = [
  {
    code: 'IV',
    name: 'Initial Visit',
    isClientRequired: true,
    permission: [
      'Case Manager',
      'Registered Nurse',
      'MSW',
      'Director of Nurse',
      'LPN',
      'Medical Director',
      'Chaplain',
    ],
  },
  {
    code: 'PRN',
    name: 'PRN',
    isClientRequired: true,
    permission: [
      'Case Manager',
      'Registered Nurse',
      'Director of Nurse',
      'LPN',
      'Medical Director',
      'Chaplain',
      'MSW',
    ],
  },
  {
    code: 'DC',
    name: 'Discharge',
    isClientRequired: true,
    permission: ['Case Manager', 'Registered Nurse', 'Director of Nurse'],
  },
  {
    code: 'SUP',
    name: 'Supervisory Visit',
    isClientRequired: true,
    permission: ['Case Manager', 'Registered Nurse', 'Director of Nurse'],
  },
  {
    code: 'HUV',
    name: 'HUV',
    isClientRequired: true,
    permission: ['Case Manager', 'Registered Nurse', 'Director of Nurse'],
  },
  {
    code: 'SFV',
    name: 'SFV',
    isClientRequired: true,
    permission: [
      'Case Manager',
      'Registered Nurse',
      'Director of Nurse',
      'LPN',
    ],
  },
  {
    code: 'IDT-PR',
    name: 'IDT Meeting In Person',
    isClientRequired: false,
    permission: ['*'],
  },
  {
    code: 'IDT-NT',
    name: 'IDT Meeting Thru Notes',
    isClientRequired: false,
    permission: ['*'],
  },
  {
    code: 'IDT-PH',
    name: 'IDT Meeting Via Phone',
    isClientRequired: false,
    permission: ['*'],
  },
  { code: 'OC', name: 'On-Call', isClientRequired: false, permission: ['*'] },
  {
    code: 'RC',
    name: 'Recertification Visit',
    isClientRequired: true,
    permission: [
      'Case Manager',
      'Registered Nurse',
      'Director of Nurse',
      'Chaplain',
      'MSW',
    ],
  },
  {
    code: 'SM',
    name: 'Staff Meeting',
    isClientRequired: false,
    permission: ['*'],
  },
  {
    code: 'IN',
    name: 'In-Service',
    isClientRequired: false,
    permission: ['*'],
  },
  {
    code: 'EV',
    name: 'Evaluation Visit',
    isClientRequired: true,
    permission: [
      'Case Manager',
      'Registered Nurse',
      'Director of Nurse',
      'Nurse Practioner',
      'MSW',
      'Chaplain',
    ],
  },
  {
    code: 'SWV',
    name: 'Social Worker Visit',
    isClientRequired: true,
    permission: ['MSW'],
  },
  {
    code: 'RV',
    name: 'Regular Visit',
    isClientRequired: true,
    permission: [
      'Certified Nurse Assistant',
      'Case Manager',
      'Registered Nurse',
      'MSW',
      'Director of Nurse',
      'LPN',
      'Medical Director',
      'Chaplain',
    ],
  },
  {
    code: 'BV',
    name: 'Bereavement Visit',
    isClientRequired: true,
    permission: ['Chaplain', 'Bereavement'],
  },
  {
    code: 'F/UV',
    name: 'Follow Up Visit',
    isClientRequired: true,
    permission: [
      'Case Manager',
      'MSW',
      'Director of Nurse',
      'Registered Nurse',
      'LPN',
      'Medical Director',
      'Chaplain',
    ],
  },
  {
    code: 'O',
    name: 'Orientation',
    isClientRequired: false,
    permission: ['*'],
  },
  {
    code: 'VV',
    name: 'Volunteer Visit',
    isClientRequired: true,
    permission: ['Volunteer'],
  },
  {
    code: 'DPV',
    name: 'Death pronouncement',
    isClientRequired: true,
    permission: ['Case Manager', 'Registered Nurse', 'Director of Nurse'],
  },
  {
    code: 'SOC',
    name: 'SOC/Assessment',
    isClientRequired: true,
    permission: [
      'Case Manager',
      'Registered Nurse',
      'Director of Nurse',
      'Chaplain',
      'MSW',
    ],
  },
  {
    code: 'APV',
    name: 'Admission Visit',
    isClientRequired: true,
    permission: ['Case Manager', 'Registered Nurse', 'Director of Nurse'],
  },
  {
    code: 'REA',
    name: 'Reassessment Visit',
    isClientRequired: true,
    permission: ['Case Manager', 'Registered Nurse', 'Director of Nurse'],
  },
  {
    code: 'ATD',
    name: 'Attendance',
    isClientRequired: false,
    permission: [
      'Administrative Manager',
      'Case Manager',
      'Director of Nurse',
      'Registered Nurse',
      'Office Manager',
      'Administrator',
    ],
  },
  { code: 'OTH', name: 'Other', isClientRequired: false, permission: ['*'] },
]
